language: node_js

branches:
 only:
    - publish-content
    - publish-rs
    - publish-overview
    - publish-multi-rend

jobs:
 include:
 - if: branch = publish-content AND type = push
   env:
    - URL="https://w3c.github.io/epub-specs/epub33/snapshot/epub-33/ECHIDNA"
    - DECISION="https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-20-epub#resolution2"
    - secure: "<KEY FOR EPUB 33>"
   script:
     - curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN_CONTENT";
     - echo "ok"
 - if: branch = publish-rs AND type = push
   env:
    - URL="https://w3c.github.io/epub-specs/epub33/snapshot/epub-rs-33/ECHIDNA"
    - DECISION="https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-20-epub#resolution2"
    - secure: "<KEY FOR EPUB RS 33>"
   script:
     - curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN_RS";
     - echo "ok"
 - if: branch = publish-overview AND type = push
   env:
    - URL="https://w3c.github.io/epub-specs/epub33/snapshot/epub-overview-33/ECHIDNA"
    - DECISION="https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-20-epub#resolution2"
    - secure: "<KEY FOR EPUB OVERVIEW>"
   script:
     - curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN_OVERVIEW";
     - echo "ok"
 - if: branch = publish-multi-rend AND type = push
   env:
    - URL="https://w3c.github.io/epub-specs/epub33/snapshot/epub-multi-rend-11/ECHIDNA"
    - DECISION="https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-20-epub#resolution2"
    - secure: "<KEY FOR EPUB MULTI REND>"
   script:
     - curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN_MULTI_REND";
     - echo "ok"

